# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:asdsadsa
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'playground_sc'
    subscriptionId: '441bdda5-40a4-4332-9efd-33390f802cb8'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PlaygroundWebApp-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/driv3r-web/TrainingRepo/main/CreateWebApp/azuredeploy.json'
    csmParametersFile: 'https://raw.githubusercontent.com/driv3r-web/TrainingRepo/main/CreateWebApp/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
 
